Bb dev assgn5.2
Mishanull/DCA1-VIA_Event_Association pull request #12
Opened 2024-03-28 16:29 UTC by banny99

UC: 1-9, command and handlers

2024-03-29 15:56 UTC, Mishanull commented
There are 3 commits in this PR instead of one, why does it include my commits as well?

2024-03-29 16:35 UTC, Mishanull requested changes

2024-03-29 16:35 UTC, Mishanull commented on src/Core/ViaEventsAssociation.Core.Application/CommandDispatching/Commands/Event/CreateEventCommand.cs
> +
`internal CreatorId creatorId { get; private init; }`
`internal FromTo fromTo {get; private init;}`
The creatorId needs to be there mandatorily, The fromTo is up to you. If you don't wanna set it here, add a default value for this field to the event.

2024-03-29 16:35 UTC, Mishanull commented on src/Core/ViaEventsAssociation.Core.Application/CommandDispatching/Commands/Event/CreateEventCommand.cs
> +    {
```
var result = new Result<CreateEventCommand>(null); 
var cIdResult = TId.FromString<CreatorId>(creatorId);
var fromToResult = FromTo.Create(start, end);
result.collectFromMultiple(cIdResult, fromToResult);
if(result.isErrorResult()) {
  return result;
}

return new Result<GuestIsInvitedToEventCommand>(new GuestIsInvitedToEventCommand(currentTime)
{
    CreatorId = cIdResult.Value!,
    FromTo = fromToResult.Value!
});
```

2024-03-29 16:35 UTC, Mishanull commented on src/Core/ViaEventsAssociation.Core.Application/CommandDispatching/Commands/Event/CreateEventCommand.cs
> +    public static Result<CreateEventCommand> Create(ICurrentTime currentTime)
```suggestion
    public static Result<CreateEventCommand> Create(ICurrentTime currentTime, string creatorId, Date start, Date end)
```

2024-03-29 16:35 UTC, Mishanull commented on src/Core/ViaEventsAssociation.Core.Application/CommandDispatching/Handlers/Event/CreateEventHandler.cs
> +        if (veaEventResult.IsErrorResult())
and to be able to create the event here either create an overload for the Create method, where you include fromTo and creatorId, or modfiy the current one (risky).

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
> +        }
newline after if

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
> +        }
same throughout this file:))

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
Hmm maybe we shouldn't keep this one. We already have a fake repo implementation. I see you did it as you would a normal repository in a sense. But it doesn't need to be this fleshed out. 
As you may have seen in the other repositories, the methods should just return a value, a default one. We do not care about how they are implemented, we just want them to return something that we expect imo.

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/Features/Event/ActivateEventTests/ActivateEventHandlerTest.cs
> +        // _uow.SaveChangesAsync();
remove this comment

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/Features/Event/CreateEventTests/CreateEventCommandTest.cs
> +    //there is no way to fail this test !?
update once you've modified the create event command

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/Features/Event/CreateEventTests/CreateEventHandlerTest.cs
> +    }
update with a failure scenario once you modify the handler

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/Features/Event/UpdateFromToTests/UpdateFromToHandlerTest.cs
> +        //Act: execute the command
newline between act and assert

2024-03-29 16:35 UTC, Mishanull commented on Tests/UnitTests/Features/Event/UpdateFromToTests/UpdateFromToHandlerTest.cs
> +        //Act: execute the command
throughout the file

2024-03-30 09:43 UTC, banny99 commented on src/Core/ViaEventsAssociation.Core.Application/CommandDispatching/Commands/Event/CreateEventCommand.cs
> +
but cant it be without any From-To if it is draft?

2024-03-30 10:17 UTC, banny99 commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
but shouldnt that fake one has a list as a storage instead of the DB? how can I use the Find method then? Find should not just return new Event. 
I want to save sth to the repo (file, list, DB, ..,.whatever) and then when I modify that one, e.g. make it public then I want to fetch the one from the repo and check if that one was set to public

2024-03-30 15:19 UTC, Mishanull commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
the way I thought of it is that we only care about the result, whether it is there or not, not about what the actual logic is. It is true that this is how a repo should work, but faking it should only mean returning a dummy value, normally. It suits our case. The actual repo we will test when we do it. Same for the logic you just mentioned. Checking whether it is public is not necessary at this level, since the core domain logic is already validated. We can keep this one as well since you are using it many places and refactoring everything might be lengthy.

2024-03-30 15:22 UTC, Mishanull approved these changes
all good imo

2024-03-30 16:09 UTC, banny99 commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
alrgiht. i see your point now. Should I redo it?

2024-03-30 21:27 UTC, Mishanull commented on Tests/UnitTests/FakeServices/FakeVeaEventRepositoryImpl.cs
up to you really, if you have the time, we could argue that we made two in parallel

2024-03-31 14:24 UTC, merged